quarkus:
  datasource:
    db-kind: mysql
    username: bifos
    password: bifos_pass

    reactive:
      url: vertx-reactive:mysql://localhost/piudb

  hibernate-orm:
    database:
      generation: drop-and-create